server:
  port: 7777

spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: false # flase = Queue；true = topic (默认false)


#自己定义队列名
myqueue: booot-acticemq